# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

repos:
  - repo: local
    hooks:
    - id: code-formatting-with-spotless
      name: code-formatting-with-spotless
      entry: ./hooks/pre-commit
      language: system
